apiVersion: apps/v1
kind: Deployment
metadata:
  name: dss-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dss-api
  template:
    metadata:
      labels:
        app: dss-api
    spec:
      containers:
      - name: dss-api
        image: digibuild.azurecr.io/emot/dss-api:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000